#!/usr/bin/env bash
set -e

CMD="$(node -e '
const x = String(process.argv[1])
let m
if (x.match(/^\d+$/)) {
  console.log(`gh run watch ${x}`)
} else if (m = x.match(/([^/]+)\/([^/]+)\/actions\/runs\/(\d+)/)) {
  console.log(`gh run watch ${m[3]} --repo=${m[1]}/${m[2]}`)
} else {
  console.error("Invalid build ID or run URL")
  process.exit(1)
}
' -- "$1")"

if $CMD --exit-status
then
  echo "[Build succeeded]"
  say "Build succeeded."
else
  echo -e "\033[1;31m[Build failed]\033[0m"
  say 'Build failed! Attention, build failed!'
fi